### ISSUE TITLE
Not updated yet for 1.4...

### ISSUE THREAD

**Issue by ZandercraftGames** [adeynes/cucumber#3]
Well then, hate to be rude but if it isnt updated yet, update it...

**Comment by adeynes** [comment]
Hi,
That's only the README, it has nothing to do with the plugin. When I push changes to `stable`, I update the README. Today I pushed changes (1.3.2-1.5.0) to `stable` and consequently updated the README. When I'm developing a feature, said development is more important to me than updating some documentation. As it turns out, you should only be using code in the `stable` branch anyways (the releases on Poggit and GitHub), for which the README is always up-to-date.
Either way, the plugin will work just fine, even if a couple lines in a table detailing command usage are slightly out-of-date.
